name: koha-dev
services:
    workplace:
        build: ./services/workplace
        tmpfs:
            - /tmp
        env_file: .env
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ../koha:/workplace/koha
